// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package Main.proto;

/**
 * Protobuf type {@code UserUpdate}
 */
public  final class UserUpdate extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:UserUpdate)
        UserUpdateOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UserUpdate.newBuilder() to construct.
  private UserUpdate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UserUpdate() {
    userId_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UserUpdate(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            userId_ = s;
            break;
          }
          case 18: {
            Main.proto.userRequest.Builder subBuilder = null;
            if (userDetails_ != null) {
              subBuilder = userDetails_.toBuilder();
            }
            userDetails_ = input.readMessage(Main.proto.userRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(userDetails_);
              userDetails_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Main.proto.UserService.internal_static_UserUpdate_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Main.proto.UserService.internal_static_UserUpdate_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Main.proto.UserUpdate.class, Main.proto.UserUpdate.Builder.class);
  }

  public static final int USERID_FIELD_NUMBER = 1;
  private volatile Object userId_;
  /**
   * <code>string userId = 1;</code>
   */
  public String getUserId() {
    Object ref = userId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      userId_ = s;
      return s;
    }
  }
  /**
   * <code>string userId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    Object ref = userId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      userId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERDETAILS_FIELD_NUMBER = 2;
  private Main.proto.userRequest userDetails_;
  /**
   * <code>.userRequest userDetails = 2;</code>
   */
  public boolean hasUserDetails() {
    return userDetails_ != null;
  }
  /**
   * <code>.userRequest userDetails = 2;</code>
   */
  public Main.proto.userRequest getUserDetails() {
    return userDetails_ == null ? Main.proto.userRequest.getDefaultInstance() : userDetails_;
  }
  /**
   * <code>.userRequest userDetails = 2;</code>
   */
  public Main.proto.userRequestOrBuilder getUserDetailsOrBuilder() {
    return getUserDetails();
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getUserIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userId_);
    }
    if (userDetails_ != null) {
      output.writeMessage(2, getUserDetails());
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getUserIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userId_);
    }
    if (userDetails_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getUserDetails());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Main.proto.UserUpdate)) {
      return super.equals(obj);
    }
    Main.proto.UserUpdate other = (Main.proto.UserUpdate) obj;

    boolean result = true;
    result = result && getUserId()
        .equals(other.getUserId());
    result = result && (hasUserDetails() == other.hasUserDetails());
    if (hasUserDetails()) {
      result = result && getUserDetails()
          .equals(other.getUserDetails());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId().hashCode();
    if (hasUserDetails()) {
      hash = (37 * hash) + USERDETAILS_FIELD_NUMBER;
      hash = (53 * hash) + getUserDetails().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Main.proto.UserUpdate parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Main.proto.UserUpdate parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Main.proto.UserUpdate parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Main.proto.UserUpdate parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Main.proto.UserUpdate parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Main.proto.UserUpdate parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Main.proto.UserUpdate parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Main.proto.UserUpdate parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Main.proto.UserUpdate parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Main.proto.UserUpdate parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Main.proto.UserUpdate parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Main.proto.UserUpdate parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Main.proto.UserUpdate prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code UserUpdate}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:UserUpdate)
      UserUpdateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Main.proto.UserService.internal_static_UserUpdate_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Main.proto.UserService.internal_static_UserUpdate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Main.proto.UserUpdate.class, Main.proto.UserUpdate.Builder.class);
    }

    // Construct using Main.proto.UserUpdate.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      userId_ = "";

      if (userDetailsBuilder_ == null) {
        userDetails_ = null;
      } else {
        userDetails_ = null;
        userDetailsBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Main.proto.UserService.internal_static_UserUpdate_descriptor;
    }

    @Override
    public Main.proto.UserUpdate getDefaultInstanceForType() {
      return getDefaultInstance();
    }

    @Override
    public Main.proto.UserUpdate build() {
      Main.proto.UserUpdate result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public Main.proto.UserUpdate buildPartial() {
      Main.proto.UserUpdate result = new Main.proto.UserUpdate(this);
      result.userId_ = userId_;
      if (userDetailsBuilder_ == null) {
        result.userDetails_ = userDetails_;
      } else {
        result.userDetails_ = userDetailsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Main.proto.UserUpdate) {
        return mergeFrom((Main.proto.UserUpdate)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Main.proto.UserUpdate other) {
      if (other == getDefaultInstance()) return this;
      if (!other.getUserId().isEmpty()) {
        userId_ = other.userId_;
        onChanged();
      }
      if (other.hasUserDetails()) {
        mergeUserDetails(other.getUserDetails());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Main.proto.UserUpdate parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Main.proto.UserUpdate) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object userId_ = "";
    /**
     * <code>string userId = 1;</code>
     */
    public String getUserId() {
      Object ref = userId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string userId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string userId = 1;</code>
     */
    public Builder setUserId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string userId = 1;</code>
     */
    public Builder clearUserId() {
      
      userId_ = getDefaultInstance().getUserId();
      onChanged();
      return this;
    }
    /**
     * <code>string userId = 1;</code>
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userId_ = value;
      onChanged();
      return this;
    }

    private Main.proto.userRequest userDetails_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        Main.proto.userRequest, Main.proto.userRequest.Builder, Main.proto.userRequestOrBuilder> userDetailsBuilder_;
    /**
     * <code>.userRequest userDetails = 2;</code>
     */
    public boolean hasUserDetails() {
      return userDetailsBuilder_ != null || userDetails_ != null;
    }
    /**
     * <code>.userRequest userDetails = 2;</code>
     */
    public Main.proto.userRequest getUserDetails() {
      if (userDetailsBuilder_ == null) {
        return userDetails_ == null ? Main.proto.userRequest.getDefaultInstance() : userDetails_;
      } else {
        return userDetailsBuilder_.getMessage();
      }
    }
    /**
     * <code>.userRequest userDetails = 2;</code>
     */
    public Builder setUserDetails(Main.proto.userRequest value) {
      if (userDetailsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        userDetails_ = value;
        onChanged();
      } else {
        userDetailsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.userRequest userDetails = 2;</code>
     */
    public Builder setUserDetails(
        Main.proto.userRequest.Builder builderForValue) {
      if (userDetailsBuilder_ == null) {
        userDetails_ = builderForValue.build();
        onChanged();
      } else {
        userDetailsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.userRequest userDetails = 2;</code>
     */
    public Builder mergeUserDetails(Main.proto.userRequest value) {
      if (userDetailsBuilder_ == null) {
        if (userDetails_ != null) {
          userDetails_ =
            Main.proto.userRequest.newBuilder(userDetails_).mergeFrom(value).buildPartial();
        } else {
          userDetails_ = value;
        }
        onChanged();
      } else {
        userDetailsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.userRequest userDetails = 2;</code>
     */
    public Builder clearUserDetails() {
      if (userDetailsBuilder_ == null) {
        userDetails_ = null;
        onChanged();
      } else {
        userDetails_ = null;
        userDetailsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.userRequest userDetails = 2;</code>
     */
    public Main.proto.userRequest.Builder getUserDetailsBuilder() {
      
      onChanged();
      return getUserDetailsFieldBuilder().getBuilder();
    }
    /**
     * <code>.userRequest userDetails = 2;</code>
     */
    public Main.proto.userRequestOrBuilder getUserDetailsOrBuilder() {
      if (userDetailsBuilder_ != null) {
        return userDetailsBuilder_.getMessageOrBuilder();
      } else {
        return userDetails_ == null ?
            Main.proto.userRequest.getDefaultInstance() : userDetails_;
      }
    }
    /**
     * <code>.userRequest userDetails = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Main.proto.userRequest, Main.proto.userRequest.Builder, Main.proto.userRequestOrBuilder> 
        getUserDetailsFieldBuilder() {
      if (userDetailsBuilder_ == null) {
        userDetailsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Main.proto.userRequest, Main.proto.userRequest.Builder, Main.proto.userRequestOrBuilder>(
                getUserDetails(),
                getParentForChildren(),
                isClean());
        userDetails_ = null;
      }
      return userDetailsBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:UserUpdate)
  }

  // @@protoc_insertion_point(class_scope:UserUpdate)
  private static final Main.proto.UserUpdate DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Main.proto.UserUpdate();
  }

  public static Main.proto.UserUpdate getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserUpdate>
      PARSER = new com.google.protobuf.AbstractParser<UserUpdate>() {
    @Override
    public UserUpdate parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UserUpdate(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UserUpdate> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<UserUpdate> getParserForType() {
    return PARSER;
  }

  @Override
  public Main.proto.UserUpdate getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

