// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package Main.proto;

public interface UserRequestIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserRequestId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   */
  String getUserId();
  /**
   * <code>string userId = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();
}
