// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package Main.proto;

public interface UserListLimitOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserListLimit)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 page = 1;</code>
   */
  int getPage();

  /**
   * <code>int32 limit = 2;</code>
   */
  int getLimit();
}
