// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package Main.proto;

public interface UserRestProtoCollOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserRestProtoColl)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .userProto user_rest_protos = 1;</code>
   */
  java.util.List<Main.proto.userProto> 
      getUserRestProtosList();
  /**
   * <code>repeated .userProto user_rest_protos = 1;</code>
   */
  Main.proto.userProto getUserRestProtos(int index);
  /**
   * <code>repeated .userProto user_rest_protos = 1;</code>
   */
  int getUserRestProtosCount();
  /**
   * <code>repeated .userProto user_rest_protos = 1;</code>
   */
  java.util.List<? extends Main.proto.userProtoOrBuilder> 
      getUserRestProtosOrBuilderList();
  /**
   * <code>repeated .userProto user_rest_protos = 1;</code>
   */
  Main.proto.userProtoOrBuilder getUserRestProtosOrBuilder(
      int index);
}
